[colors-dark]
alpha = 0.9
alpha-mode = matching

cursor = 111117 dfdfdf
foreground=bfbfbf
background=111117

#selection-foreground = use normal text
selection-background = 272740

scrollback-indicator = 6bc7dd 171720
search-box-no-match = fe1858 171720
search-box-match = e1ea8c 171720

regular0=151515
regular1=fe1858
regular2=50ea7b
regular3=e1ea8c
regular4=207d8a
regular5=ee79c6
regular6=6bc7dd
regular7=dddddd

bright0=555555
bright1=ff4595
bright2=91ffaa
bright3=ffdfcc
bright4=4099a5
bright5=ffaae4
bright6=9ffaff
bright7=eeeeee

dim0=000000
dim1=e10044
dim2=42e66c
dim3=d9e67e
dim4=0d515e
dim5=e66ac3
dim6=7cdde8
dim7=cccccc
