#
#  Super Efficient Keyboard Config For Turkish Qwerty Keyboard
#


[ids]
*

###################################################################################

#
# MAIN
#

[main]

# status : working : capslock , leftcontrol, space
###################################################################################

# Use Capslock as ESC and Ctrl
capslock = overload(control, esc)

# Use left Ctrl for capslock
leftcontrol = capslock

# I dont need uparrow anymore
up = layer(shift)

# Zooming
kpplus = C-kpplus
kpminus = C-kpminus

# Extended keyboard features with rightalt
rightalt = layer(extended)

# Macros layout
esc = oneshot(macros_layout)

###################################################################################

#
# EXTENDED FEATURES
#

[extended:G]

#status: working fine
###################################################################################

# Use hjkl instead of arrow keys
h = left
j = down
k = up
l = right

# shift tab with altgr tab. its easier for me
tab = S-tab

# brackets 
# {
a = G-7
# }
s = G-0

# (
d = S-8
# )
f = S-9

# [
w = G-8
# ]
e = G-9

# <
r = 102nd
# >
t = S-102nd

# Other useful symbols
# /
u = S-7
# :
m = S-/
# $
n = G-4
# "
i = `
# '
o = S-2
# =
b = S-0
# ;
; = S-\
# _
y = S-=

###################################################################################

#
# Macros Layout
#

# I hate using trq

[macros_layout]

###################################################################################

esc = noop

# TTY switching

1 = C-A-f1
2 = C-A-f2
3 = C-A-f3
4 = C-A-f4
5 = C-A-f5
6 = C-A-f6

## Git

# git add && gs enter
a = macro(g't space add space / space leftshift+6 leftshift+6 space gs enter)
# git commit -m "" esc i
c = macro(g't space comm't space =m space `` esc ')
# git push  main esc b h i
p = macro(g't space push space space ma'n esc b h ')
# git pull  main esc b h i
u = macro(g't space pull space space ma'n esc b h ')










