#
#  Super Efficient Keyboard Config For Turkish Qwerty Keyboard
#


[ids]
*

###################################################################################

#
# MAIN
#

[main]

# status : working : capslock , leftcontrol, space
###################################################################################

# Use Capslock as ESC and Ctrl
capslock = overload(control, esc)

# Use left Ctrl for capslock
leftcontrol = capslock

# Extended keyboard features with rightalt
rightalt = layer(extended)

# Zooming
kpplus = C-kpplus
kpminus = C-kpminus

###################################################################################

#
# EXTENDED FEATURES
#

[extended:G]

#status: working fine
###################################################################################

# Use hjkl instead of arrow keys
h = left
j = down
k = up
l = right

# Easy shift+
tab = S-tab
ctrl = C-S

# brackets 
# {
a = G-7
# }
s = G-0

# (
d = S-8
# )
f = S-9

# [
w = G-8
# ]
e = G-9

# <
r = 102nd
# >
t = S-102nd

# Other useful symbols
# /
u = S-7
# :
m = S-/
# $
n = G-4
# "
i = `
# '
o = S-2
# =
b = S-0
# ;
; = S-\













