#
#  Super Efficient Keyboard Config For Turkish Qwerty Keyboard
#


[ids]
*

###################################################################################

#
# MAIN
#

[main]

# status : working : capslock , leftcontrol, space
###################################################################################

# Use Capslock as ESC and Ctrl
capslock = overload(control, esc)

# Use left Ctrl for capslock
leftcontrol = capslock

# Extended keyboard features with rightalt
rightalt = layer(extended)

# Zooming
kpplus = C-kpplus
kpminus = C-kpminus

###################################################################################

#
# EXTENDED FEATURES
#

[extended:G]

#status: working fine
###################################################################################

# Use hjkl instead of arrow keys
h = left
j = down
k = up
l = right

c = S-tab
v = tab

# brackets 
# {
a = G-7
# [
s = G-8
# (
d = S-8
# <
f = 102nd

# }
w = G-0
# ]
e = G-9
# )
r = S-9
# >
t = S-102nd

# Other useful symbols
# /
u = S-7
# :
m = S-/
# $
n = G-4
# "
i = `
# '
o = S-2













