exec-once = hyprctl setcursor LyraB-cursors 32
exec-once = GTK_THEME=CybrCyanMateria ADW_DEBUG_COLOR_SCHEME=prefer-dark regreet

windowrule {
    name = regreet-fs
    match:class = ^(regreet)$
    fullscreen = true
}

animations {
        bezier = linear, 0, 0, 1, 1

        animation = windows, 1, 4, linear, popin
        animation = windowsIn, 1, 4, linear, popin
        animation = windowsOut, 1, 4, linear, popin
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

input {
        kb_layout = tr
}
