[global]
width = 250
height = (75, 200)
notification_limit = 10
origin = center
frame_width = 2
padding = 10
font = Caskaydia Cove NF 14
corner_radius = 6
hide_duplicate_count = true
format = "%s %b"
timeout = 2
alignment = center
vertical_alignment = center

# Progress Bar settings
progress_bar = true
progress_bar_height = 10
progress_bar_frame_width = 1
progress_bar_min_width = 250
progress_bar_max_width = 250
progress_bar_corner_radius = 4
#highlight = "#6BC7DD"
highlight = "#50EA7B,#6bc7dd"

[urgency_normal]
background = "#111117bb"
foreground = "#6BC7DD"
frame_color = "#171720ee"

[volumeformat]
appname = "volume"
format = "<span size='15500' rise='-1000'>%s</span> %b"ighlight = "#6BC7DD"
