#
# Layer Rules
#

# All of them below just applies blur & animation

layerrule {
        name = rofi
        match:namespace = ^(rofi)$
        blur = on
        ignore_alpha = 0.5
        dim_around = 0.3 
        animation = slide left
}

layerrule {
        name = dunst
        match:namespace = notifications
        blur = on
        dim_around = 0.3 
        ignore_alpha = 0.5
        animation = slide right
}

layerrule {
        name = waybar
        match:namespace = waybar
        animation = slide top
}

layerrule {
        name = wallpaper
        match:namespace = wallpaper
        animation = fade
}
