#
# Workspace Rules
#

# Transparency for Rofi
windowrule {
    name = rofi-transparency
    match:class = ^(Rofi)$
    opacity = 0.8 override
}

# Satty window large & floating
windowrule {
        name = satty-float
        match:class = ^(com.gabm.satty)$
        float = true
        size = 1320 700
}

# Fuckup maximizing
windowrule {
        name = suppress-maximize-events
        match:class = .*

        suppress_event = maximize
}

# Fix some dragging issues with XWayland
# Comes from default hyprland config
windowrule {
        name = fix-xwayland-drags
        match:class = ^$
        match:title = ^$
        match:xwayland = true
        match:float = true
        match:fullscreen = false
        match:pin = false

        no_focus = true
}

# File pickers & Confirmation Popups
windowrule {
    name = file-pickers
    match:title = .*(Choose|Open|Select|Save|Dosya|Seç|Kaydet|Yükle|Aç).*
    float = true
    size = 1000 600
    center = true
}

windowrule {
        name = confirmation-popups
        match:title = .*(Confirm|Warn|Error|ERROR|Onayla|Uyarı|Hata|HATA).*
        float = true
        center = true
}


## Special Workspaces

# Web
windowrule {
        name = zen-workspace
        match:class = app.zen_browser.zen
        workspace = 3
}

windowrule {
        name = heluim-workspace
        match:class = helium
        workspace = 3
}

# AI
windowrule {
        name = gemini-workspace
        match:class = gemini
        workspace = 4
}

# Notes
windowrule {
        name = notes-workspace
        match:class = notes
        workspace = 5
}
