#!/bin/bash

options="App Launcher\nWifi Manager"
selected=$(echo -ne "$options" | rofi -dmenu -i -p "Select:")
which rofi-wifi
# rofi-* scripts are at ~/.local/bin (as a symlink)
case $selected in
	"App Launcher")
		rofi -show drun
		;;

	"Wifi Manager")
		~/.local/bin/rofi-wifi
		;;
	*) 
                echo wtf is happening?
                ;;
esac
