#!/bin/bash

options="App Launcher\nWifi Manager\nColor Picker\nANSI Picker"
selected=$(echo -ne "$options" | rofi -dmenu -i -p "Select:")

# rofi-* scripts are at ~/.local/bin (as a symlink)
case $selected in
	"App Launcher")
		/home/melon/.local/bin/rofi-launcher
		;;

	"Wifi Manager")
		/home/melon/.local/bin/rofi-wifi
		;;

	"Color Picker")
		/home/melon/.local/bin/rofi-color-picker
		;;
	"ANSI Picker")
		/home/melon/.local/bin/rofi-ansi-picker
		;;
	*) ;;
esac
