#
# Hyprland
#

# Variables
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/variables.conf

# Monitors
source = ~/.config/hypr/config/monitors.conf

# General Settings
source = ~/.config/hypr/config/settings/settings.conf

# Keyboard Related
source = ~/.config/hypr/config/settings/keyboard.conf
source = ~/.config/hypr/config/settings/keybinds.conf

# Autostart
source = ~/.config/hypr/config/autostart.conf

# Visual Settings
source = ~/.config/hypr/config/visual/visual.conf
source = ~/.config/hypr/config/visual/animations.conf
source = ~/.config/hypr/config/visual/layouts.conf

# Rules
source = ~/.config/hypr/config/rules/windowrules.conf
source = ~/.config/hypr/config/rules/layerrules.conf
source = ~/.config/hypr/config/rules/workspacerules.conf


