[colors.primary]
foreground="#bfbfbf"
background="#111117"

[colors.normal]
black="#151515"
red="#fe1858"
green="#50ea7b"
yellow="#e1ea8c"
blue="#207d8a"
magenta="#ee79c6"
cyan="#6bc7dd"
white="#dddddd"

[colors.bright]
black="#555555"
red="#ff4595"
green="#91ffaa"
yellow="#ffdfcc"
blue="#4099a5"
magenta="#ffaae4"
cyan="#9ffaff"
white="#eeeeee"

[colors.dim]
black="#000000"
red="#e10044"
green="#42e66c"
yellow="#d9e67e"
blue="#0d515e"
magenta="#e66ac3"
cyan="#7cdde8"
white="#cccccc"
