#
# Animations
#

animations {
    enabled = yes

    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1
    bezier = wait,           0.87, 0.57, 0.55, 0.26
    bezier = slow,              0.97, 0.74, 0.63, 1
    bezier = ease, 0.3, 0.28, 0.32, 1.03

    animation = global,       1,     10,    default
    animation = workspaces,   1,     2.5,     wait,    slidefadevert 50%
    animation = windows,      1,     4,     slow
    animation = windowsIn, 1, 4, ease, slide
    animation = windowsOut, 1, 4, ease, slide
    animation = border,       1,     3,  default
    animation = borderangle, 0, 1, default
    animation = fade,       1,     6,  almostLinear
    animation = layers,       1,     4,  slow, slide bottom
}


