#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = swaybg -i ~/dotfiles/images/wallpaper.jpg -m fill
exec-once = dunst
exec-once = cliphist wipe
exec-once = wl-paste --type text --watch cliphist -max-items 100 store
exec-once = wl-paste --type image --watch cliphist -max-items 100 store
exec-once = avizo-service
exec-once = hyprctl setcursor LyraB-cursors 32

#########################
### DASHBOARD STARTUP ###
#########################

exec-once = [workspace 1 silent] $terminal --class btop_tui -e btop
exec-once = [workspace 1 silent] $terminal --class clock_tui -e tty-clock -C 6
exec-once = [workspace 1 silent] $terminal --class pipes_tui -e pipes-rs --delay 55
exec-once = [workspace 1 silent] $terminal --class bonsai_tui -e sh -c "sleep 0.2 && cbonsai -l"
exec-once = [workspace 1 silent] $terminal --class home_terminal
