#################
### AUTOSTART ###
#################

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && hyprshade auto
exec-once = waybar
exec-once = swaybg -i ~/dotfiles/images/wallpaper.jpg -m fill
exec-once = dunst
exec-once = cliphist wipe
exec-once = wl-paste --type text --watch cliphist -max-items 100 store
exec-once = wl-paste --type image --watch cliphist -max-items 100 store
exec-once = avizo-service
exec-once = hyprctl setcursor LyraB-cursors 32
exec-once = foot --server
exec-once = mkdir -p /tmp/gemini # gemini will dont access home directory

#########################
### DASHBOARD STARTUP ###
#########################

#exec-once = [workspace 1 silent] $terminal --class btop_tui -e btop
#exec-once = [workspace 1 silent] $terminal --class clock_tui -e tty-clock -c -C 6
#exec-once = [workspace 1 silent] $terminal --class pipes_tui -e pipes-rs -t 0.05 -p 3 
#exec-once = [workspace 1 silent] $terminal --class bonsai_tui -e sh -c "sleep 0.2 && cbonsai -l"
#exec-once = [workspace 1 silent] $terminal --class home_terminal

#####################
### STARTUP SOUND ###
#####################

exec-once = sh -c 'sleep 2 && mpv $sound_theme/stereo/desktop-login.*'
