###################
###  VARIABLES  ###
###################

# https://wiki.hypr.land/Configuring/Keywords/

$terminal = alacritty
$fileManagerTUI = alacritty -e yazi
$fileManager = thunar
$menu = ~/dotfiles/.config/rofi/bin/rofi-menu
$browser = flatpak run app.zen_browser.zen
$helium = /opt/helium-browser-bin/helium
$osd = ~/dotfiles/scripts/osd/osd.sh

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_THEME,LyraB-cursors
env = XCURSOR_SIZE,32
env = HYPRCURSOR_SIZE,32
env = LIBVA_DRIVER_NAME, iHD
env = XDG_SESSION_TYPE, wayland
env = GBM_BACKEND,drm
env = GTK_THEME,Adwaita:dark
env = QT_QPA_PLATFORMTHEME,qt6ct

