###################
###  VARIABLES  ###
###################

# https://wiki.hypr.land/Configuring/Keywords/

$terminal = footclient
$fileManagerTUI = $terminal yazi
$fileManager = thunar
$menu = ~/dotfiles/.config/rofi/bin/rofi-menu
$browser = flatpak run app.zen_browser.zen          # Firefox based
$browser_alt = /opt/helium-browser-bin/helium       # Chromium based
$osd = ~/dotfiles/scripts/osd/osd.sh
$sound_theme = ~/.local/share/sounds/modern-minimal-ui-sounds # Sound theme path
$gemini = $terminal --working-directory /tmp/gemini --app-id gemini gemini
$notes = $terminal --app-id notes --working-directory ~/documents/obsidian nvim TODOS.md
$rogue = $terminal -o tweak.font-monospace-warn=no -o main.font="square:size=14" sh -c "if [ -f ~/rogue.save ]; then rogue -r; else rogue; fi"

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_THEME,LyraB-cursors
env = XCURSOR_SIZE,32
env = HYPRCURSOR_SIZE,32
env = LIBVA_DRIVER_NAME, iHD
env = XDG_SESSION_TYPE, wayland
env = GBM_BACKEND,drm
env = GTK_THEME,CybrCyanMateria
env = QT_QPA_PLATFORMTHEME,qt6ct
env = CANBERRA_XDG_SOUND_THEME_NAME,modern-minimal-ui-sounds
env = GTK_MODULES,canberra-gtk-module
