#
#  Variables
#

$terminal = footclient
$fileManagerTUI = $terminal yazi
$fileManager = thunar
$menu = ~/dotfiles/.config/rofi/bin/rofi-menu
$browser = flatpak run app.zen_browser.zen          # Firefox based
$browser_alt = /opt/helium-browser-bin/helium       # Chromium based
$osd = ~/dotfiles/scripts/osd/osd.sh
$sound_theme = ~/.local/share/sounds/modern-minimal-ui-sounds # Sound theme path
$gemini = $terminal --title "Gemini" --working-directory /tmp/gemini --app-id gemini gemini
$notes = $terminal --title "Notes" --app-id notes --working-directory ~/documents/obsidian nvim TODOS.md
$rogue = $terminal --title "Rogue" -o tweak.font-monospace-warn=no -o main.font="square:size=12.5" sh -c "if [ -f ~/rogue.save ]; then rogue -r; else rogue; fi"

