###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow


##############################
### WINDOWS AND WORKSPACES ###
##############################

layerrule {
        name = rofi
        match:namespace = ^(rofi)$
        blur = on
        ignore_alpha = 0.5
        dim_around = 0.3 
        xray = on
        animation = slide left
}

layerrule {
        name = dunst
        match:namespace = notifications
        blur = on
        dim_around = 0.3 
        ignore_alpha = 0.5
        animation = slide right
}

layerrule {
        name = waybar
        match:namespace = waybar
        animation = slide top
}

layerrule {
        name = wallpaper
        match:namespace = wallpaper
        animation = fade
}

windowrule {
    name = rofi-transparency
    match:class = ^(Rofi)$
    opacity = 0.8 override
}

windowrule {
        name = satty-float
        match:class = ^(com.gabm.satty)$
        float = true
        size = 1320 700
}

# Ignore maximize requests from all apps. You'll probably like this.
windowrule {
        name = suppress-maximize-events
        match:class = .*

        suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
        name = fix-xwayland-drags
        match:class = ^$
        match:title = ^$
        match:xwayland = true
        match:float = true
        match:fullscreen = false
        match:pin = false

        no_focus = true
}

# Hyprland-run windowrule
windowrule {
        name = move-hyprland-run

        match:class = hyprland-run

        move = 20 monitor_h-120
        float = yes
}

windowrule {
    name = file-pickers-by-title
    match:title = ^(Choose|Open|Select|Save|Dosya|Seç|Kaydet|Yükle).*
    float = true
    size = 1000 600
    center = true
}

##########################
## Special Workspaces   ##
##########################

windowrule {
        name = zen-workspace
        match:class = app.zen_browser.zen
        workspace = 3
}

windowrule {
        name = heluim-workspace
        match:class = helium
        workspace = 3
}

windowrule {
        name = gemini-workspace
        match:class = gemini
        workspace = 4
}

windowrule {
        name = notes-workspace
        match:class = notes
        workspace = 5
}

#########################
### DASHBOARD LAYOUT  ###
#########################

windowrule {
    name = dash-btop
    match:class = ^(btop_tui)$
    float = true
    size = 664 719
    move = 690 37
    workspace = 1
}

windowrule {
    name = dash-clock
    match:class = ^(clock_tui)$
    float = true
    size = 287 152
    move = 12 37
    workspace = 1
}

windowrule {
    name = dash-pipes
    match:class = ^(pipes_tui)$
    float = true
    size = 287 210
    move = 12 203
    workspace = 1
}

windowrule {
    name = dash-bonsai
    match:class = ^(bonsai_tui)$
    float = true
    size = 363 376
    move = 313 37
    workspace = 1
}

windowrule {
    name = dash-terminal
    match:class = ^(home_terminal)$
    float = true
    size = 664 329
    move = 12 427
    workspace = 1
}


