# gitfetch configuration file
# See docs/providers.md for provider configuration
# See docs/colors.md for color customization

[DEFAULT]
username = HasanAgitUnal
cache_expiry_minutes = 5
provider = github
provider_url = https://api.github.com

[COLORS]
white = #FFFFFF
